server.port: 8081
server:
  ssl:
    key-store: classpath:aijishenli.xyz.jks
    key-store-password: 0gx2p07u9vsz4l
APPID: wx6a012f422b0fb1db
APP_SECRET: 09954c0750fbe913d553effab8b1ffbb

redis:
  #超时时间
  timeout: 10000ms
  #服务器地址，虚拟机的，或者远程服务器
  host: localhost
  #服务器端口
  port: 6379
  #数据库
  database: 0
  #密码，没有配密码可以不配置
  # password: lhs
  lettuce:
    pool:
      #最大连接数，默认8
      max-active: 1024
      #最大连接阻塞等待时间，默认-1
      max-wait: 10000ms
      #最大空闲连接
      max-idle: 200
      #最小空闲连接
      min-idle: 5

spring:
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.13:3306/accounting?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 520syyufonlyone
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 1430180905@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: tlixqzxthgfrhcgc # 配置申请到的授权码(刚让复制的授权码)
    # pop3-password: tlixqzxthgfrhcgc
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 1430180905@qq.com # 发送方邮件，配在yml中可方便更改
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #短信
  shortMessage:
    appCode: 99a68cab482c4e90ba7940164363e3c1
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms
    method: POST
